# Generated by Django 4.2.6 on 2024-07-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solve', '0002_alter_minigame_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minigame',
            old_name='gamemode',
            new_name='gamemode1',
        ),
        migrations.AddField(
            model_name='minigame',
            name='gamemode2',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
