# Generated by Django 4.2.6 on 2024-07-21 21:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solve', '0003_rename_gamemode_minigame_gamemode1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minigame',
            name='gamemode1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=4),
        ),
    ]
