# Generated by Django 4.2.6 on 2024-09-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solve', '0004_alter_minigame_gamemode1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minigame',
            old_name='total_problems',
            new_name='timemode',
        ),
        migrations.RemoveField(
            model_name='minigame',
            name='time_spent',
        ),
    ]
