# Generated by Django 4.2.6 on 2024-10-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solve', '0005_rename_total_problems_minigame_timemode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minigame',
            old_name='timemode',
            new_name='time_duration',
        ),
        migrations.RemoveField(
            model_name='minigame',
            name='gamemode1',
        ),
        migrations.RemoveField(
            model_name='minigame',
            name='gamemode2',
        ),
    ]
