# Generated by Django 4.2.6 on 2024-10-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solve', '0006_rename_timemode_minigame_time_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minigame',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
