# Generated by Django 4.2.6 on 2024-07-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeruser',
            name='fastest_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playeruser',
            name='games_played',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playeruser',
            name='personal_best',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playeruser',
            name='problem_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
