# Generated by Django 4.2.6 on 2024-10-08 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_playeruser_fastest_time_playeruser_games_played_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeruser',
            name='fastest_time',
        ),
        migrations.RemoveField(
            model_name='playeruser',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='playeruser',
            name='personal_best',
        ),
        migrations.RemoveField(
            model_name='playeruser',
            name='problem_count',
        ),
    ]
