# Generated by Django 4.2.6 on 2025-08-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_playeruser_fastest_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
